### ISSUE TITLE
Ghostscript error when trying to print boleto pdf

### ISSUE THREAD

**Issue by rvalyi** [akretion/boleto_cnab_api#8]
When using the existing Docker image and trying the Bash basic example you may get this error:

```
Puma caught this error: Error: /invalidfileaccess in --run--                           
 Operand stack:                                                               
    (/usr/local/bundle/bundler/gems/brcobranca-9bb3defe9e07/lib/brcobranca/boleto/template/../../arquivos/templates/modelo_generico.eps)   (r)
 Execution stack:                                                           
    %interp_exit   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   run   false   1   %stopped_
push   1974   1   3   %oparray_pop   1973   1   3   %oparray_pop   1961   1   3   %oparray_pop   1817   1   3   %oparray_pop   --nostringval--
 %errorexec_pop   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   1974   1   3   %oparray_pop
  run                                                                    
 Dictionary stack:                                                           
    --dict:730/1123(ro)(G)--   --dict:0/20(G)--   --dict:244/300(L)--           
 Current allocation mode is local                                         
 Last OS error: Permission denied                                      
 Current file position is 4112                                              
 (RGhost::RenderException)                                                       
/usr/local/bundle/gems/rghost-0.9.7/lib/rghost/ruby_ghost_engine.rb:89:in `render'
/usr/local/bundle/gems/rghost-0.9.7/lib/rghost/document.rb:238:in `render'
/usr/local/bundle/gems/rghost-0.9.7/lib/rghost/document.rb:258:in `render_stream'
/usr/local/bundle/bundler/gems/brcobranca-9bb3defe9e07/lib/brcobranca/boleto/template/rghost.rb:118:in `modelo_generico_multipage'
/usr/local/bundle/bundler/gems/brcobranca-9bb3defe9e07/lib/brcobranca/boleto/template/rghost.rb:43:in `lote'
/usr/src/app/lib/boleto_api.rb:118:in `block (2 levels) in <class:Server>'
/usr/local/bundle/gems/grape-1.3.3/lib/grape/endpoint.rb:59:in `call'    
```

Seems due to the ghostscript version, see https://github.com/kivanio/brcobranca/issues/213#issuecomment-611175477

I will try to downgrade Ghostscript in our image to fix it.

**Comment by rvalyi** [comment]
fixed by https://github.com/akretion/boleto_cnab_api/commit/77732cce012414ee6cde39e8382f8a53fc0dc0d0
